<?php #CONFIGURATORE 
if (!session_id()) {
	session_start();
}

?>
<head>
	<meta charset="utf-8">
	<title>Sail Colors Configurator</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<!-- the above line hides the compatibility button in IE9 -->

	<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0" />

	<link href="../assets/img/shared/favicon.ico" rel="shortcut icon" type="image/x-icon" />

	<link href="../assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	<link href="../assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />

	<link href="../assets/css//myPatches.css" rel="stylesheet" />


	<!-- html2canvas library -->
	<script src="../assets/js/html2canvas.min.js"></script>

	<!-- jsPDF library -->
	<script src="../assets/js/jsPDF/dist/jspdf.umd.js"></script>
	
	<style>
		
		body{
			font-family: "Helvetica",Arial,serif;
			
		}
		.container{
			text-align: center;
		}
		.wrapper{
			max-width: 800px;
			margin: auto;
			background-color: #fff;
			color: #000000ad;
			box-shadow: 0 2px 5px 0 rgb(0 0 0 / 16%), 0 2px 10px 0 rgb(0 0 0 / 12%);
			border-radius: 5px;
			padding: 10px;
			margin-top: 15px;
		}
		.wrapper img{
			max-width: 100%;
		}

		.wrapper button{
			float: right;
			border: 1px solid #087bff;
			background-color: #087bff;
			color: #fff;
			padding: 4px 8px;
			font-size: 15px;
		}
		.wrapper button:hover{
			background-color: #fff;
			color: #087bff;
		}
		.box{
			border:1px solid #aaa;
			border-radius:10px;
			padding: 10px;
			text-align:center;
			margin-bottom: 20px;
		}
		.logo{
			text-align: center;
		    margin: 5px auto 25px;
		    width: 100%;
		    border-bottom:1px solid #bbb;
		}
		.logo img{
		    width: 350px;
		}
		.model-title{
			font-size: 22px;
		    margin: 15px;
		}
		H3{
			font-size: 16px;
		}
		.create{
			background-color: transparent !important;
			color:#666 !important;
			border:1px solid #666 !important;
			border-radius:5px;
			padding:5px;
			cursor: pointer;
		}
		.create:hover{
			color:#000 !important;
		}
		.table-title{
			border-bottom:1px solid #bbb;
			text-align:center;
		}
		.table{
			width: 90%;
			margin: auto;
			text-align: center;
			margin-bottom: 20px;
		}

		table{
			margin: auto;
			min-width: 600px;
		}
		.table th{
			padding: 2px;
			line-height: 20px;
			text-align: left;
			vertical-align: top;
			border-bottom: 1px solid #ccc;
			font-size: 15px;
			font-weight: 500;
		}
		.table td{
			padding: 4px;
			line-height: 10px;
			text-align: left;
			vertical-align: top;
			border-bottom: 1px solid #ddd;
			font-size: 13px;
		}
		.offset1 {
	        margin: auto;
	        text-align: center;
	        margin-top: 20px;
	        max-width: 1160px;
    	}
    	.titleTable{
			margin-bottom:10px;
			margin-top:150px;
			font-size:20px;
		}

    	#footer{
    		text-align:center;
    		margin: auto;
    		max-width: 1160px;
    	}
    	@media (max-width: 1200px) {
		    #footer {
		        max-width: 600px;
		        
		    }
		}
		@media (max-width: 979px) {
		    #footer {
		        max-width: 600px;
		        
		    }
		}
    	@media (max-width: 768px) {
		    #footer {
		        max-width: 600px;;
		    }
		    table {
			    margin: auto;
			    min-width: 90%;
			}
		}
		@media (max-width: 400px) {
		    .table td{
			padding: 2px;
			line-height: 9px;
			font-size: 8px;
			}
			.model-title{
			font-size: 16px;
		    margin: 10px;
			}
			H3 {
			    font-size: 12px;
			    line-height: 0px;

			}
			.table th {
			    padding: 0px;
			    line-height: 12px;
			    font-size: 10px;
			}
			#downloadPdf{
				display:none;
			}
			.titleTable{
				margin-bottom:10px;
				margin-top:10px;
			}
		}
    	hr.footerHr{
			border: 1px solid #a9a9a95c;
			max-width: 1200px;
			margin:5 auto;
		}
		.label-important, .badge-important {
		    background-color: #b8b8b8;
		}
		
		


	</style>

	

	<script>
		var namefile = localStorage.getItem("model").replace(" ", "-").toLowerCase();
		window.jsPDF = window.jspdf.jsPDF;

		function Convert_HTML_To_PDF() {


			var doc = new jsPDF();

			
			var elementHTML = document.querySelector("#contentToPrint");

			//doc.setFont('ProtestStrike-Regular', 'normal'),
			doc.html(elementHTML, {
				callback: function(doc) {
					// Save the PDF
					doc.setProperties({
	                    title: namefile, //Title for File/PDF from localStorage
	                    subject: 'Sail Color Configurator',
	                    author: 'Icaro2000',
	                    keywords: 'Hanggliders',
	                    creator: 'Generated by jsPDF'
                	});
					doc.save(namefile+'.pdf');
					//window.open(doc.output('bloburl'),namefile+'.pdf');
				},

				margin: [10, 10, 10, 10],
				autoPaging: 'text',
				x: 0,
				y: 0,
				width: 190, // Target width in the PDF document
				windowWidth: 675 // Window width in CSS pixels
			});
		}
	</script>
</head>
<body>
	<div id="content" class="container-fluid">
		<div class="row-fluid">
			<div class="navbar ">
				<div class="navbar-inner">

					<a class=" pull-left" href="http://www.icaro2000.com">
						<img src="../assets/img/icaro2000-logo.png" width="400"/>
					</a>
					<ul id="menu" class="nav nav-pills pull-left">
						<li class="divider"></li>

						<li class="divider divider-vertical"></li>
					</ul>

				</div>
			</div>
		</div>
	</div>
	<div class="container">

		

		<div class="wrapper">
			<div id="contentToPrint">
				<div class="logo">
					<img src="../assets/img/icaro2000-logo.png"/> 
				</div>
				
				<center><div id="model" class="model-title" style="text-transform: uppercase;"></div></center>

				<div class="box">
					<H3>TOP</H3>
					<img id="img0" src="" alt="Side TOP" width="100%">
				</div>


				<div class="box">
					<H3>BOTTOM</H3>
					<img id="img1" src="" alt="Side BOTTOM" width="100%">
				</div>

				<center><div class="model-title titleTable"><b>COLOR CHART</b></div></center>
				<div class="table" style="margin-bottom:60px;" id="jsonTable"></div>

			</div>
		</div>
		<div class="offset1">
			<button id="downloadPdf" class="btn btn-success" onclick="Convert_HTML_To_PDF();">Download PDF</button>
			<input type="button" value="Close" class="btn btn-inverse" onclick="location.href = 'javascript:window.close()'">
		</div>
	</div>

	<script>
		if(localStorage.getItem("side0")=='' || localStorage.getItem("side1")==''){alert("Data not found!\pPlease try again");}
		document.getElementById("img0").src = localStorage.getItem("side0");
		document.getElementById("img1").src = localStorage.getItem("side1");
		document.getElementById("model").innerHTML = "<b>"+localStorage.getItem("model")+"</b>";

		let obj = JSON.parse(localStorage.getItem("JSONtable"));
		let table = '<table><thead><tr><th>Side</th><th class="TT">ID</th><th>Panel</th><th>Your choice</th></tr></thead><tbody>';
		itemSide='';
		obj.forEach(function(item){
			if(item.Side=='bott'){itemSide='Bottom'}else{itemSide="Top";}
			table+='<tr>';
			table+='<td>'+itemSide+'</td>';
			table+='<td>'+item.ID+'</td>';
			table+='<td>'+item.Panel+'</td>';
			table+='<td>'+item.Fill+'</td>';
			table+='</tr>';
		});
		table+='</tbody></table>';
		document.getElementById("jsonTable").innerHTML = table;
	</script>
<?php include("../includes/footer.php");?>
</body>
</html>
